/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 562021
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form main_frame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneMain = new javax.swing.JTabbedPane();
        jPanelHome = new javax.swing.JPanel();
        jLabelHomeHeading = new javax.swing.JLabel();
        jLabelEmployeeCount = new javax.swing.JLabel();
        jLabelPayrollTotal = new javax.swing.JLabel();
        jLabelWorkforceHours = new javax.swing.JLabel();
        jButtonUpgrade = new javax.swing.JButton();
        jButtonDirectRemove = new javax.swing.JButton();
        jButtonDirectAdd = new javax.swing.JButton();
        jButtonDirectSearch = new javax.swing.JButton();
        jLabelCurrentCEO = new javax.swing.JLabel();
        jPanelAdd = new javax.swing.JPanel();
        jLabelAddHeading = new javax.swing.JLabel();
        jLabelAddEmployeeNumber = new javax.swing.JLabel();
        jTextFieldAddEmployeeNumber = new javax.swing.JTextField();
        jLabelAddFirstName = new javax.swing.JLabel();
        jTextFieldAddFirstName = new javax.swing.JTextField();
        jLabelAddLastName = new javax.swing.JLabel();
        jTextFieldAddLastName = new javax.swing.JTextField();
        jLabelAddSex = new javax.swing.JLabel();
        jRadioButtonAddSexM = new javax.swing.JRadioButton();
        jRadioButtonAddSexF = new javax.swing.JRadioButton();
        jRadioButtonAddSexOther = new javax.swing.JRadioButton();
        jRadioButtonAddSexPreferNot = new javax.swing.JRadioButton();
        jLabelAddLocation = new javax.swing.JLabel();
        jRadioButtonAddLocationToronto = new javax.swing.JRadioButton();
        jRadioButtonAddLocationMississauga = new javax.swing.JRadioButton();
        jRadioButtonAddLocationHalifax = new javax.swing.JRadioButton();
        jRadioButtonAddLocationMiami = new javax.swing.JRadioButton();
        jLabelAddDeductRate = new javax.swing.JLabel();
        jTextFieldAddDeductRate = new javax.swing.JTextField();
        jPanelAddFullTimeEmployee = new javax.swing.JPanel();
        jRadioButtonAddFullTimeEmployee = new javax.swing.JRadioButton();
        jLabelAddFullTimeEmployeeYearlySalary = new javax.swing.JLabel();
        jTextFieldAddFullTimeEmployeeYearlySalary = new javax.swing.JTextField();
        jButtonAddSubmit = new javax.swing.JButton();
        jPanelAddPartTimeEmployee = new javax.swing.JPanel();
        jRadioButtonAddPartTimeEmployee = new javax.swing.JRadioButton();
        jLabelAddPartTimeEmployeeHourlyWage = new javax.swing.JLabel();
        jTextFieldAddPartTimeEmployeeHourlyWage = new javax.swing.JTextField();
        jLabelAddPartTimeEmployeeHoursPerWeek = new javax.swing.JLabel();
        jTextFieldAddPartTimeEmployeeHoursPerWeek = new javax.swing.JTextField();
        jLabelAddPartTimeEmployeeWeeksPerYear = new javax.swing.JLabel();
        jTextFieldAddPartTimeEmployeeWeeksPerYear = new javax.swing.JTextField();
        jPanelStatistics = new javax.swing.JPanel();
        jPanelView = new javax.swing.JPanel();
        jScrollPaneViewAllEmployees = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanelSearch = new javax.swing.JPanel();
        jLabelSearchHeading = new javax.swing.JLabel();
        jLabelSearchEmployeeNumber = new javax.swing.JLabel();
        jTextFieldSearchEmployeeNumber = new javax.swing.JTextField();
        jLabelSearchEmployeeName = new javax.swing.JLabel();
        jTextFieldSearchEmployeeName = new javax.swing.JTextField();
        jLabelSearchOR = new javax.swing.JLabel();
        jButtonSearchSubmit = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemFileNew = new javax.swing.JMenuItem();
        jMenuItemFileOpen = new javax.swing.JMenuItem();
        jMenuItemFileSave = new javax.swing.JMenuItem();
        jMenuItemFileSaveAs = new javax.swing.JMenuItem();
        jMenuWindow = new javax.swing.JMenu();
        jMenuItemWindowPreferences = new javax.swing.JMenuItem();
        jMenuHelp = new javax.swing.JMenu();
        jMenuItemHelpCheckForUpdates = new javax.swing.JMenuItem();
        jMenuItemHelpAbout = new javax.swing.JMenuItem();
        jMenuItemHelpTutorial = new javax.swing.JMenuItem();
        jMenuItemHelpDocumentation = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabelHomeHeading.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jLabelHomeHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHomeHeading.setText("CompanyA Employee Database");

        jLabelEmployeeCount.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelEmployeeCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEmployeeCount.setText("100 Employees");

        jLabelPayrollTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelPayrollTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPayrollTotal.setText("$1,000,000 yearly payroll");

        jLabelWorkforceHours.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelWorkforceHours.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelWorkforceHours.setText("300 weekly hours");

        jButtonUpgrade.setFont(new java.awt.Font("Comic Sans MS", 3, 48)); // NOI18N
        jButtonUpgrade.setText("UPGRADE NOW!");
        jButtonUpgrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpgradeActionPerformed(evt);
            }
        });

        jButtonDirectRemove.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButtonDirectRemove.setText("FIRE EMPLOYEE");
        jButtonDirectRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDirectRemoveActionPerformed(evt);
            }
        });

        jButtonDirectAdd.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButtonDirectAdd.setText("ADD EMPLOYEE");
        jButtonDirectAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDirectAddActionPerformed(evt);
            }
        });

        jButtonDirectSearch.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButtonDirectSearch.setText("ADJUST EMPLOYEE");
        jButtonDirectSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDirectSearchActionPerformed(evt);
            }
        });

        jLabelCurrentCEO.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelCurrentCEO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCurrentCEO.setText("Current CEO: Asdf Asdf");

        javax.swing.GroupLayout jPanelHomeLayout = new javax.swing.GroupLayout(jPanelHome);
        jPanelHome.setLayout(jPanelHomeLayout);
        jPanelHomeLayout.setHorizontalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHomeLayout.createSequentialGroup()
                .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPayrollTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelHomeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelHomeHeading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelEmployeeCount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelWorkforceHours, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonUpgrade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanelHomeLayout.createSequentialGroup()
                                .addComponent(jButtonDirectRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonDirectSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonDirectAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelCurrentCEO, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanelHomeLayout.setVerticalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelHomeHeading)
                .addGap(18, 18, 18)
                .addComponent(jLabelEmployeeCount)
                .addGap(18, 18, 18)
                .addComponent(jLabelPayrollTotal)
                .addGap(18, 18, 18)
                .addComponent(jLabelWorkforceHours)
                .addGap(18, 18, 18)
                .addComponent(jLabelCurrentCEO)
                .addGap(47, 47, 47)
                .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDirectRemove)
                    .addComponent(jButtonDirectAdd)
                    .addComponent(jButtonDirectSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addComponent(jButtonUpgrade)
                .addGap(60, 60, 60))
        );

        jTabbedPaneMain.addTab("Home", jPanelHome);

        jLabelAddHeading.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabelAddHeading.setText("Add Employee");

        jLabelAddEmployeeNumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelAddEmployeeNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelAddEmployeeNumber.setText("Employee Number:");

        jTextFieldAddEmployeeNumber.setText("jTextField1");

        jLabelAddFirstName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelAddFirstName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelAddFirstName.setText("First Name:");

        jTextFieldAddFirstName.setText("jTextField1");

        jLabelAddLastName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelAddLastName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelAddLastName.setText("Last Name:");

        jTextFieldAddLastName.setText("jTextField1");

        jLabelAddSex.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelAddSex.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelAddSex.setText("Sex:");

        jRadioButtonAddSexM.setText("M");
        jRadioButtonAddSexM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAddSexMActionPerformed(evt);
            }
        });

        jRadioButtonAddSexF.setText("F");

        jRadioButtonAddSexOther.setText("Other");

        jRadioButtonAddSexPreferNot.setText("Prefer Not To Say");

        jLabelAddLocation.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelAddLocation.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelAddLocation.setText("Location:");

        jRadioButtonAddLocationToronto.setText("Toronto");

        jRadioButtonAddLocationMississauga.setText("Mississauga");

        jRadioButtonAddLocationHalifax.setText("Halifax");

        jRadioButtonAddLocationMiami.setText("Miami");

        jLabelAddDeductRate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelAddDeductRate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelAddDeductRate.setText("Deduct Rate:");

        jTextFieldAddDeductRate.setText("jTextField1");

        jRadioButtonAddFullTimeEmployee.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonAddFullTimeEmployee.setText("Full Time Employee");
        jRadioButtonAddFullTimeEmployee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButtonAddFullTimeEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAddFullTimeEmployeeActionPerformed(evt);
            }
        });

        jLabelAddFullTimeEmployeeYearlySalary.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelAddFullTimeEmployeeYearlySalary.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelAddFullTimeEmployeeYearlySalary.setText("Yearly Salary:");

        jTextFieldAddFullTimeEmployeeYearlySalary.setText("jTextField1");

        jButtonAddSubmit.setText("Submit (Will pop up a confirmation window with the employee info to be submitted)");

        javax.swing.GroupLayout jPanelAddFullTimeEmployeeLayout = new javax.swing.GroupLayout(jPanelAddFullTimeEmployee);
        jPanelAddFullTimeEmployee.setLayout(jPanelAddFullTimeEmployeeLayout);
        jPanelAddFullTimeEmployeeLayout.setHorizontalGroup(
            jPanelAddFullTimeEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddFullTimeEmployeeLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabelAddFullTimeEmployeeYearlySalary)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldAddFullTimeEmployeeYearlySalary, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAddFullTimeEmployeeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAddFullTimeEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonAddSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanelAddFullTimeEmployeeLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jRadioButtonAddFullTimeEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(379, 379, 379))
        );
        jPanelAddFullTimeEmployeeLayout.setVerticalGroup(
            jPanelAddFullTimeEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddFullTimeEmployeeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonAddFullTimeEmployee)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAddFullTimeEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAddFullTimeEmployeeYearlySalary)
                    .addComponent(jTextFieldAddFullTimeEmployeeYearlySalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addComponent(jButtonAddSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        jRadioButtonAddPartTimeEmployee.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonAddPartTimeEmployee.setText("Part Time Employee");
        jRadioButtonAddPartTimeEmployee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButtonAddPartTimeEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAddPartTimeEmployeeActionPerformed(evt);
            }
        });

        jLabelAddPartTimeEmployeeHourlyWage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelAddPartTimeEmployeeHourlyWage.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelAddPartTimeEmployeeHourlyWage.setText("Hourly Wage:");

        jTextFieldAddPartTimeEmployeeHourlyWage.setText("Will be uneditable if full time employee is selected");

        jLabelAddPartTimeEmployeeHoursPerWeek.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelAddPartTimeEmployeeHoursPerWeek.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelAddPartTimeEmployeeHoursPerWeek.setText("Hours per Week:");

        jTextFieldAddPartTimeEmployeeHoursPerWeek.setText("jTextField1");

        jLabelAddPartTimeEmployeeWeeksPerYear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelAddPartTimeEmployeeWeeksPerYear.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelAddPartTimeEmployeeWeeksPerYear.setText("Weeks per Year:");

        jTextFieldAddPartTimeEmployeeWeeksPerYear.setText("jTextField1");

        javax.swing.GroupLayout jPanelAddPartTimeEmployeeLayout = new javax.swing.GroupLayout(jPanelAddPartTimeEmployee);
        jPanelAddPartTimeEmployee.setLayout(jPanelAddPartTimeEmployeeLayout);
        jPanelAddPartTimeEmployeeLayout.setHorizontalGroup(
            jPanelAddPartTimeEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddPartTimeEmployeeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRadioButtonAddPartTimeEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(379, 379, 379))
            .addGroup(jPanelAddPartTimeEmployeeLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanelAddPartTimeEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAddPartTimeEmployeeLayout.createSequentialGroup()
                        .addComponent(jLabelAddPartTimeEmployeeWeeksPerYear)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldAddPartTimeEmployeeWeeksPerYear, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelAddPartTimeEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanelAddPartTimeEmployeeLayout.createSequentialGroup()
                            .addComponent(jLabelAddPartTimeEmployeeHoursPerWeek)
                            .addGap(18, 18, 18)
                            .addComponent(jTextFieldAddPartTimeEmployeeHoursPerWeek, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelAddPartTimeEmployeeLayout.createSequentialGroup()
                            .addComponent(jLabelAddPartTimeEmployeeHourlyWage)
                            .addGap(18, 18, 18)
                            .addComponent(jTextFieldAddPartTimeEmployeeHourlyWage, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelAddPartTimeEmployeeLayout.setVerticalGroup(
            jPanelAddPartTimeEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddPartTimeEmployeeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonAddPartTimeEmployee)
                .addGap(18, 18, 18)
                .addGroup(jPanelAddPartTimeEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAddPartTimeEmployeeHourlyWage)
                    .addComponent(jTextFieldAddPartTimeEmployeeHourlyWage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAddPartTimeEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAddPartTimeEmployeeHoursPerWeek)
                    .addComponent(jTextFieldAddPartTimeEmployeeHoursPerWeek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAddPartTimeEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAddPartTimeEmployeeWeeksPerYear)
                    .addComponent(jTextFieldAddPartTimeEmployeeWeeksPerYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(160, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelAddLayout = new javax.swing.GroupLayout(jPanelAdd);
        jPanelAdd.setLayout(jPanelAddLayout);
        jPanelAddLayout.setHorizontalGroup(
            jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAddHeading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelAddLayout.createSequentialGroup()
                        .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelAddEmployeeNumber)
                            .addComponent(jLabelAddFirstName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelAddLastName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelAddSex, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelAddLocation, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelAddDeductRate, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelAddLayout.createSequentialGroup()
                                .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelAddLayout.createSequentialGroup()
                                        .addComponent(jRadioButtonAddSexM)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButtonAddSexF)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButtonAddSexOther)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButtonAddSexPreferNot))
                                    .addGroup(jPanelAddLayout.createSequentialGroup()
                                        .addComponent(jRadioButtonAddLocationToronto)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButtonAddLocationMississauga)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButtonAddLocationHalifax)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButtonAddLocationMiami))
                                    .addComponent(jTextFieldAddDeductRate, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextFieldAddEmployeeNumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                .addComponent(jTextFieldAddLastName, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldAddFirstName, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addContainerGap())
            .addGroup(jPanelAddLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanelAddFullTimeEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanelAddPartTimeEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelAddLayout.setVerticalGroup(
            jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAddHeading)
                .addGap(8, 8, 8)
                .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAddEmployeeNumber)
                    .addComponent(jTextFieldAddEmployeeNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAddFirstName)
                    .addComponent(jTextFieldAddFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAddLastName)
                    .addComponent(jTextFieldAddLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAddSex)
                    .addComponent(jRadioButtonAddSexM)
                    .addComponent(jRadioButtonAddSexF)
                    .addComponent(jRadioButtonAddSexOther)
                    .addComponent(jRadioButtonAddSexPreferNot))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAddLocation)
                    .addComponent(jRadioButtonAddLocationToronto)
                    .addComponent(jRadioButtonAddLocationMississauga)
                    .addComponent(jRadioButtonAddLocationHalifax)
                    .addComponent(jRadioButtonAddLocationMiami))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAddDeductRate)
                    .addComponent(jTextFieldAddDeductRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelAddFullTimeEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelAddPartTimeEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTabbedPaneMain.addTab("Add", jPanelAdd);

        javax.swing.GroupLayout jPanelStatisticsLayout = new javax.swing.GroupLayout(jPanelStatistics);
        jPanelStatistics.setLayout(jPanelStatisticsLayout);
        jPanelStatisticsLayout.setHorizontalGroup(
            jPanelStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 752, Short.MAX_VALUE)
        );
        jPanelStatisticsLayout.setVerticalGroup(
            jPanelStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        jTabbedPaneMain.addTab("Statistics", jPanelStatistics);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Employee Number", "First Name", "Last Name", "Location", "Net Income"
            }
        ));
        jScrollPaneViewAllEmployees.setViewportView(jTable1);

        jLabel12.setText("Use tiles to display employee information if <br/>capable of doing so with code to repeat the tiles");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelViewLayout = new javax.swing.GroupLayout(jPanelView);
        jPanelView.setLayout(jPanelViewLayout);
        jPanelViewLayout.setHorizontalGroup(
            jPanelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelViewLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPaneViewAllEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelViewLayout.setVerticalGroup(
            jPanelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelViewLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneViewAllEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        jTabbedPaneMain.addTab("View All", jPanelView);

        jLabelSearchHeading.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabelSearchHeading.setText("Search");

        jLabelSearchEmployeeNumber.setText("Employee Number");

        jTextFieldSearchEmployeeNumber.setText("jTextField4");

        jLabelSearchEmployeeName.setText("Employee Name");

        jTextFieldSearchEmployeeName.setText("jTextField5");

        jLabelSearchOR.setText("OR");

        jButtonSearchSubmit.setText("Search");
        jButtonSearchSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchSubmitActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Employee Info:\nAsdf Asdf\nLocation: Mississauga\netc.\n\n");
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanelSearchLayout = new javax.swing.GroupLayout(jPanelSearch);
        jPanelSearch.setLayout(jPanelSearchLayout);
        jPanelSearchLayout.setHorizontalGroup(
            jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchLayout.createSequentialGroup()
                .addGroup(jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSearchLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelSearchHeading)
                            .addGroup(jPanelSearchLayout.createSequentialGroup()
                                .addComponent(jLabelSearchEmployeeNumber)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldSearchEmployeeNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(jLabelSearchOR)
                                .addGap(64, 64, 64)
                                .addComponent(jLabelSearchEmployeeName)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldSearchEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelSearchLayout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jButtonSearchSubmit))
                    .addGroup(jPanelSearchLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(297, Short.MAX_VALUE))
        );
        jPanelSearchLayout.setVerticalGroup(
            jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSearchHeading)
                .addGap(18, 18, 18)
                .addGroup(jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSearchEmployeeNumber)
                    .addComponent(jTextFieldSearchEmployeeNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSearchEmployeeName)
                    .addComponent(jTextFieldSearchEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSearchOR))
                .addGap(53, 53, 53)
                .addComponent(jButtonSearchSubmit)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(271, Short.MAX_VALUE))
        );

        jTabbedPaneMain.addTab("Search", jPanelSearch);

        jMenuFile.setText("File");
        jMenuFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFileActionPerformed(evt);
            }
        });

        jMenuItemFileNew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemFileNew.setText("New");
        jMenuFile.add(jMenuItemFileNew);

        jMenuItemFileOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemFileOpen.setText("Open");
        jMenuItemFileOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFileOpenActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemFileOpen);

        jMenuItemFileSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemFileSave.setText("Save");
        jMenuFile.add(jMenuItemFileSave);

        jMenuItemFileSaveAs.setText("Save As");
        jMenuFile.add(jMenuItemFileSaveAs);

        jMenuBar1.add(jMenuFile);

        jMenuWindow.setText("Window");

        jMenuItemWindowPreferences.setText("Preferences");
        jMenuWindow.add(jMenuItemWindowPreferences);

        jMenuBar1.add(jMenuWindow);

        jMenuHelp.setText("Help");

        jMenuItemHelpCheckForUpdates.setText("Check for Updates");
        jMenuItemHelpCheckForUpdates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHelpCheckForUpdatesActionPerformed(evt);
            }
        });
        jMenuHelp.add(jMenuItemHelpCheckForUpdates);

        jMenuItemHelpAbout.setText("About");
        jMenuHelp.add(jMenuItemHelpAbout);

        jMenuItemHelpTutorial.setText("Tutorial");
        jMenuHelp.add(jMenuItemHelpTutorial);

        jMenuItemHelpDocumentation.setText("Documentation");
        jMenuHelp.add(jMenuItemHelpDocumentation);

        jMenuBar1.add(jMenuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPaneMain, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPaneMain)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuFileActionPerformed

    private void jMenuItemFileOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFileOpenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemFileOpenActionPerformed

    private void jMenuItemHelpCheckForUpdatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHelpCheckForUpdatesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemHelpCheckForUpdatesActionPerformed

    private void jButtonSearchSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchSubmitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSearchSubmitActionPerformed

    private void jRadioButtonAddSexMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAddSexMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonAddSexMActionPerformed

    private void jButtonDirectSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDirectSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDirectSearchActionPerformed

    private void jButtonDirectAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDirectAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDirectAddActionPerformed

    private void jButtonDirectRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDirectRemoveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDirectRemoveActionPerformed

    private void jButtonUpgradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpgradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUpgradeActionPerformed

    private void jRadioButtonAddPartTimeEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAddPartTimeEmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonAddPartTimeEmployeeActionPerformed

    private void jRadioButtonAddFullTimeEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAddFullTimeEmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonAddFullTimeEmployeeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddSubmit;
    private javax.swing.JButton jButtonDirectAdd;
    private javax.swing.JButton jButtonDirectRemove;
    private javax.swing.JButton jButtonDirectSearch;
    private javax.swing.JButton jButtonSearchSubmit;
    private javax.swing.JButton jButtonUpgrade;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabelAddDeductRate;
    private javax.swing.JLabel jLabelAddEmployeeNumber;
    private javax.swing.JLabel jLabelAddFirstName;
    private javax.swing.JLabel jLabelAddFullTimeEmployeeYearlySalary;
    private javax.swing.JLabel jLabelAddHeading;
    private javax.swing.JLabel jLabelAddLastName;
    private javax.swing.JLabel jLabelAddLocation;
    private javax.swing.JLabel jLabelAddPartTimeEmployeeHourlyWage;
    private javax.swing.JLabel jLabelAddPartTimeEmployeeHoursPerWeek;
    private javax.swing.JLabel jLabelAddPartTimeEmployeeWeeksPerYear;
    private javax.swing.JLabel jLabelAddSex;
    private javax.swing.JLabel jLabelCurrentCEO;
    private javax.swing.JLabel jLabelEmployeeCount;
    private javax.swing.JLabel jLabelHomeHeading;
    private javax.swing.JLabel jLabelPayrollTotal;
    private javax.swing.JLabel jLabelSearchEmployeeName;
    private javax.swing.JLabel jLabelSearchEmployeeNumber;
    private javax.swing.JLabel jLabelSearchHeading;
    private javax.swing.JLabel jLabelSearchOR;
    private javax.swing.JLabel jLabelWorkforceHours;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JMenuItem jMenuItemFileNew;
    private javax.swing.JMenuItem jMenuItemFileOpen;
    private javax.swing.JMenuItem jMenuItemFileSave;
    private javax.swing.JMenuItem jMenuItemFileSaveAs;
    private javax.swing.JMenuItem jMenuItemHelpAbout;
    private javax.swing.JMenuItem jMenuItemHelpCheckForUpdates;
    private javax.swing.JMenuItem jMenuItemHelpDocumentation;
    private javax.swing.JMenuItem jMenuItemHelpTutorial;
    private javax.swing.JMenuItem jMenuItemWindowPreferences;
    private javax.swing.JMenu jMenuWindow;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelAdd;
    private javax.swing.JPanel jPanelAddFullTimeEmployee;
    private javax.swing.JPanel jPanelAddPartTimeEmployee;
    private javax.swing.JPanel jPanelHome;
    private javax.swing.JPanel jPanelSearch;
    private javax.swing.JPanel jPanelStatistics;
    private javax.swing.JPanel jPanelView;
    private javax.swing.JRadioButton jRadioButtonAddFullTimeEmployee;
    private javax.swing.JRadioButton jRadioButtonAddLocationHalifax;
    private javax.swing.JRadioButton jRadioButtonAddLocationMiami;
    private javax.swing.JRadioButton jRadioButtonAddLocationMississauga;
    private javax.swing.JRadioButton jRadioButtonAddLocationToronto;
    private javax.swing.JRadioButton jRadioButtonAddPartTimeEmployee;
    private javax.swing.JRadioButton jRadioButtonAddSexF;
    private javax.swing.JRadioButton jRadioButtonAddSexM;
    private javax.swing.JRadioButton jRadioButtonAddSexOther;
    private javax.swing.JRadioButton jRadioButtonAddSexPreferNot;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPaneViewAllEmployees;
    private javax.swing.JTabbedPane jTabbedPaneMain;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldAddDeductRate;
    private javax.swing.JTextField jTextFieldAddEmployeeNumber;
    private javax.swing.JTextField jTextFieldAddFirstName;
    private javax.swing.JTextField jTextFieldAddFullTimeEmployeeYearlySalary;
    private javax.swing.JTextField jTextFieldAddLastName;
    private javax.swing.JTextField jTextFieldAddPartTimeEmployeeHourlyWage;
    private javax.swing.JTextField jTextFieldAddPartTimeEmployeeHoursPerWeek;
    private javax.swing.JTextField jTextFieldAddPartTimeEmployeeWeeksPerYear;
    private javax.swing.JTextField jTextFieldSearchEmployeeName;
    private javax.swing.JTextField jTextFieldSearchEmployeeNumber;
    // End of variables declaration//GEN-END:variables
}
