/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 562021
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form main_frame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneMain = new javax.swing.JTabbedPane();
        jPanelHome = new javax.swing.JPanel();
        jLabelHomeHeading = new javax.swing.JLabel();
        jLabelHomeEmployeeCount = new javax.swing.JLabel();
        jLabelHomePayrollTotal = new javax.swing.JLabel();
        jLabelHomeWorkforceHours = new javax.swing.JLabel();
        jLabelHomeCurrentCEO = new javax.swing.JLabel();
        jButtonHomeExit = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jPanelAdd = new javax.swing.JPanel();
        jLabelAddHeading = new javax.swing.JLabel();
        jLabelAddEmployeeNumber = new javax.swing.JLabel();
        jTextFieldAddEmployeeNumber = new javax.swing.JTextField();
        jLabelAddFirstName = new javax.swing.JLabel();
        jTextFieldAddFirstName = new javax.swing.JTextField();
        jLabelAddLastName = new javax.swing.JLabel();
        jTextFieldAddLastName = new javax.swing.JTextField();
        jLabelAddSex = new javax.swing.JLabel();
        jRadioButtonAddSexM = new javax.swing.JRadioButton();
        jRadioButtonAddSexF = new javax.swing.JRadioButton();
        jRadioButtonAddSexOther = new javax.swing.JRadioButton();
        jRadioButtonAddSexPreferNot = new javax.swing.JRadioButton();
        jLabelAddLocation = new javax.swing.JLabel();
        jLabelAddDeductRate = new javax.swing.JLabel();
        jTextFieldAddDeductRate = new javax.swing.JTextField();
        jButtonAddSubmit = new javax.swing.JButton();
        jTextFieldAddPartTimeEmployeeWeeksPerYear = new javax.swing.JTextField();
        jLabelAddPartTimeEmployeeWeeksPerYear = new javax.swing.JLabel();
        jLabelAddPartTimeEmployeeHoursPerWeek = new javax.swing.JLabel();
        jTextFieldAddPartTimeEmployeeHoursPerWeek = new javax.swing.JTextField();
        jTextFieldAddPartTimeEmployeeHourlyWage = new javax.swing.JTextField();
        jLabelAddPartTimeEmployeeHourlyWage = new javax.swing.JLabel();
        jRadioButtonAddPartTimeEmployee = new javax.swing.JRadioButton();
        jTextFieldAddFullTimeEmployeeYearlySalary = new javax.swing.JTextField();
        jLabelAddFullTimeEmployeeYearlySalary = new javax.swing.JLabel();
        jRadioButtonAddFullTimeEmployee = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox();
        jPanelSearch = new javax.swing.JPanel();
        jLabelSearchHeading = new javax.swing.JLabel();
        jLabelSearchEmployeeNumber = new javax.swing.JLabel();
        jTextFieldSearchEmployeeNumber = new javax.swing.JTextField();
        jLabelSearchEmployeeName = new javax.swing.JLabel();
        jTextFieldSearchEmployeeName = new javax.swing.JTextField();
        jLabelSearchOR = new javax.swing.JLabel();
        jButtonSearchSubmit = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanelView = new javax.swing.JPanel();
        jScrollPaneViewAllEmployees = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBarMenu = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemFileNew = new javax.swing.JMenuItem();
        jMenuItemFileOpen = new javax.swing.JMenuItem();
        jMenuItemFileSave = new javax.swing.JMenuItem();
        jMenuItemFileSaveAs = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuWindow = new javax.swing.JMenu();
        jMenuItemWindowPreferences = new javax.swing.JMenuItem();
        jMenuHelp = new javax.swing.JMenu();
        jMenuItemHelpCheckForUpdates = new javax.swing.JMenuItem();
        jMenuItemHelpAbout = new javax.swing.JMenuItem();
        jMenuItemHelpTutorial = new javax.swing.JMenuItem();
        jMenuItemHelpDocumentation = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(770, 640));

        jTabbedPaneMain.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPaneMain.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPaneMain.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPaneMain.setAutoscrolls(true);

        jPanelHome.setBackground(new java.awt.Color(255, 255, 255));

        jLabelHomeHeading.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 36)); // NOI18N
        jLabelHomeHeading.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelHomeHeading.setText("CompanyA Employee Database");

        jLabelHomeEmployeeCount.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelHomeEmployeeCount.setText("100 Employees");

        jLabelHomePayrollTotal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelHomePayrollTotal.setText("$1,000,000 yearly payroll");

        jLabelHomeWorkforceHours.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelHomeWorkforceHours.setText("300 weekly hours");

        jLabelHomeCurrentCEO.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelHomeCurrentCEO.setText("Current CEO: Asdf Asdf");

        jButtonHomeExit.setBackground(new java.awt.Color(0, 0, 0));
        jButtonHomeExit.setForeground(new java.awt.Color(255, 255, 255));
        jButtonHomeExit.setText("Exit");
        jButtonHomeExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Change System");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel2.setText("Company Information:");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane1.setViewportView(jTextArea2);

        jLabel3.setText("Powered by");

        javax.swing.GroupLayout jPanelHomeLayout = new javax.swing.GroupLayout(jPanelHome);
        jPanelHome.setLayout(jPanelHomeLayout);
        jPanelHomeLayout.setHorizontalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHomeLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelHomeEmployeeCount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelHomeLayout.createSequentialGroup()
                        .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelHomePayrollTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanelHomeLayout.createSequentialGroup()
                                .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelHomeWorkforceHours, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelHomeCurrentCEO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(40, 40, 40)))
                        .addGap(275, 275, 275))
                    .addGroup(jPanelHomeLayout.createSequentialGroup()
                        .addComponent(jLabelHomeHeading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(102, 102, 102))
                    .addGroup(jPanelHomeLayout.createSequentialGroup()
                        .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jPanelHomeLayout.createSequentialGroup()
                        .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelHomeLayout.createSequentialGroup()
                                .addComponent(jButtonHomeExit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton4))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHomeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        jPanelHomeLayout.setVerticalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelHomeHeading)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelHomeEmployeeCount)
                .addGap(18, 18, 18)
                .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelHomeLayout.createSequentialGroup()
                        .addComponent(jLabelHomePayrollTotal)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelHomeWorkforceHours)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelHomeCurrentCEO)
                        .addGap(36, 36, 36)
                        .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonHomeExit)
                            .addComponent(jButton4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelHomeLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)))
                .addGap(27, 27, 27))
        );

        jTabbedPaneMain.addTab("Home", jPanelHome);

        jPanelAdd.setBackground(new java.awt.Color(255, 255, 255));

        jLabelAddHeading.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 24)); // NOI18N
        jLabelAddHeading.setText("Add Employee");

        jLabelAddEmployeeNumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelAddEmployeeNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelAddEmployeeNumber.setText("Employee Number:");

        jTextFieldAddEmployeeNumber.setText("jTextField1");

        jLabelAddFirstName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelAddFirstName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelAddFirstName.setText("First Name:");

        jTextFieldAddFirstName.setText("jTextField1");

        jLabelAddLastName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelAddLastName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelAddLastName.setText("Last Name:");

        jTextFieldAddLastName.setText("jTextField1");

        jLabelAddSex.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelAddSex.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelAddSex.setText("Sex:");

        jRadioButtonAddSexM.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButtonAddSexM.setText("M");
        jRadioButtonAddSexM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAddSexMActionPerformed(evt);
            }
        });

        jRadioButtonAddSexF.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButtonAddSexF.setText("F");

        jRadioButtonAddSexOther.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButtonAddSexOther.setText("Other");

        jRadioButtonAddSexPreferNot.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButtonAddSexPreferNot.setText("Prefer Not To Say");

        jLabelAddLocation.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelAddLocation.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelAddLocation.setText("Location:");

        jLabelAddDeductRate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelAddDeductRate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelAddDeductRate.setText("Deduct Rate:");

        jTextFieldAddDeductRate.setText("jTextField1");

        jButtonAddSubmit.setBackground(new java.awt.Color(0, 0, 0));
        jButtonAddSubmit.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAddSubmit.setText("Submit (Will pop up a confirmation window with the employee info to be submitted)");

        jTextFieldAddPartTimeEmployeeWeeksPerYear.setText("jTextField1");

        jLabelAddPartTimeEmployeeWeeksPerYear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelAddPartTimeEmployeeWeeksPerYear.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelAddPartTimeEmployeeWeeksPerYear.setText("Weeks per Year:");

        jLabelAddPartTimeEmployeeHoursPerWeek.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelAddPartTimeEmployeeHoursPerWeek.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelAddPartTimeEmployeeHoursPerWeek.setText("Hours per Week:");

        jTextFieldAddPartTimeEmployeeHoursPerWeek.setText("jTextField1");

        jTextFieldAddPartTimeEmployeeHourlyWage.setText("Will be uneditable if full time employee is selected");

        jLabelAddPartTimeEmployeeHourlyWage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelAddPartTimeEmployeeHourlyWage.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelAddPartTimeEmployeeHourlyWage.setText("Hourly Wage:");

        jRadioButtonAddPartTimeEmployee.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButtonAddPartTimeEmployee.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonAddPartTimeEmployee.setText("Part Time Employee");
        jRadioButtonAddPartTimeEmployee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButtonAddPartTimeEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAddPartTimeEmployeeActionPerformed(evt);
            }
        });

        jTextFieldAddFullTimeEmployeeYearlySalary.setText("jTextField1");

        jLabelAddFullTimeEmployeeYearlySalary.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelAddFullTimeEmployeeYearlySalary.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelAddFullTimeEmployeeYearlySalary.setText("Yearly Salary:");

        jRadioButtonAddFullTimeEmployee.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButtonAddFullTimeEmployee.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonAddFullTimeEmployee.setText("Full Time Employee");
        jRadioButtonAddFullTimeEmployee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButtonAddFullTimeEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAddFullTimeEmployeeActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mississauga", "Toronto", "Ottawa", "Halifax", "Miami" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAddLayout = new javax.swing.GroupLayout(jPanelAdd);
        jPanelAdd.setLayout(jPanelAddLayout);
        jPanelAddLayout.setHorizontalGroup(
            jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAddHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelAddLayout.createSequentialGroup()
                            .addGap(49, 49, 49)
                            .addComponent(jLabelAddLastName)
                            .addGap(18, 18, 18)
                            .addComponent(jTextFieldAddLastName))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelAddLayout.createSequentialGroup()
                            .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelAddLayout.createSequentialGroup()
                                    .addComponent(jLabelAddEmployeeNumber)
                                    .addGap(18, 18, 18))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAddLayout.createSequentialGroup()
                                    .addComponent(jLabelAddFirstName)
                                    .addGap(21, 21, 21)))
                            .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldAddFirstName)
                                .addComponent(jTextFieldAddEmployeeNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelAddLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabelAddSex)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonAddSexM)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonAddSexF)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonAddSexOther)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonAddSexPreferNot))
                    .addGroup(jPanelAddLayout.createSequentialGroup()
                        .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelAddLayout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jLabelAddLocation)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelAddLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelAddLayout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(jLabelAddFullTimeEmployeeYearlySalary)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldAddFullTimeEmployeeYearlySalary, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jRadioButtonAddFullTimeEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelAddLayout.createSequentialGroup()
                                        .addComponent(jLabelAddDeductRate)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldAddDeductRate, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(124, 124, 124)
                        .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelAddLayout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelAddLayout.createSequentialGroup()
                                            .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAddLayout.createSequentialGroup()
                                                    .addComponent(jLabelAddPartTimeEmployeeHourlyWage)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                                .addGroup(jPanelAddLayout.createSequentialGroup()
                                                    .addComponent(jLabelAddPartTimeEmployeeHoursPerWeek)
                                                    .addGap(10, 10, 10)))
                                            .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jTextFieldAddPartTimeEmployeeHoursPerWeek)
                                                .addComponent(jTextFieldAddPartTimeEmployeeHourlyWage, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(jButtonAddSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelAddLayout.createSequentialGroup()
                                        .addComponent(jLabelAddPartTimeEmployeeWeeksPerYear)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldAddPartTimeEmployeeWeeksPerYear, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jRadioButtonAddPartTimeEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelAddLayout.setVerticalGroup(
            jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabelAddHeading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAddEmployeeNumber)
                    .addComponent(jTextFieldAddEmployeeNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAddFirstName)
                    .addComponent(jTextFieldAddFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAddLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAddLastName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAddSex)
                    .addComponent(jRadioButtonAddSexM)
                    .addComponent(jRadioButtonAddSexF)
                    .addComponent(jRadioButtonAddSexOther)
                    .addComponent(jRadioButtonAddSexPreferNot))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAddLocation)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAddDeductRate)
                    .addComponent(jTextFieldAddDeductRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAddLayout.createSequentialGroup()
                        .addComponent(jRadioButtonAddFullTimeEmployee)
                        .addGap(18, 18, 18)
                        .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAddFullTimeEmployeeYearlySalary)
                            .addComponent(jTextFieldAddFullTimeEmployeeYearlySalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelAddLayout.createSequentialGroup()
                        .addComponent(jRadioButtonAddPartTimeEmployee)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAddPartTimeEmployeeHourlyWage)
                            .addComponent(jTextFieldAddPartTimeEmployeeHourlyWage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAddPartTimeEmployeeHoursPerWeek)
                            .addComponent(jTextFieldAddPartTimeEmployeeHoursPerWeek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelAddPartTimeEmployeeWeeksPerYear)
                            .addComponent(jTextFieldAddPartTimeEmployeeWeeksPerYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addComponent(jButtonAddSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jTabbedPaneMain.addTab("Add", jPanelAdd);

        jPanelSearch.setBackground(new java.awt.Color(255, 255, 255));

        jLabelSearchHeading.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 24)); // NOI18N
        jLabelSearchHeading.setText("Search");

        jLabelSearchEmployeeNumber.setText("Employee Number");

        jTextFieldSearchEmployeeNumber.setText("jTextField4");

        jLabelSearchEmployeeName.setText("Employee Name");

        jTextFieldSearchEmployeeName.setText("jTextField5");

        jLabelSearchOR.setText("OR");

        jButtonSearchSubmit.setBackground(new java.awt.Color(0, 0, 0));
        jButtonSearchSubmit.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSearchSubmit.setText("Search");
        jButtonSearchSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchSubmitActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Employee Info:\nAsdf Asdf\nLocation: Mississauga\netc.\n\n");
        jScrollPane2.setViewportView(jTextArea1);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Edit");

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Delete");

        javax.swing.GroupLayout jPanelSearchLayout = new javax.swing.GroupLayout(jPanelSearch);
        jPanelSearch.setLayout(jPanelSearchLayout);
        jPanelSearchLayout.setHorizontalGroup(
            jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchLayout.createSequentialGroup()
                .addGroup(jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSearchLayout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jButtonSearchSubmit))
                    .addGroup(jPanelSearchLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jButton1)
                        .addGap(65, 65, 65)
                        .addComponent(jButton2))
                    .addGroup(jPanelSearchLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelSearchLayout.createSequentialGroup()
                                .addComponent(jLabelSearchEmployeeNumber)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldSearchEmployeeNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(jLabelSearchOR)
                                .addGap(64, 64, 64)
                                .addComponent(jLabelSearchEmployeeName)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldSearchEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelSearchLayout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelSearchHeading))))
                .addContainerGap(231, Short.MAX_VALUE))
        );
        jPanelSearchLayout.setVerticalGroup(
            jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabelSearchHeading)
                .addGap(18, 18, 18)
                .addGroup(jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSearchEmployeeNumber)
                    .addComponent(jTextFieldSearchEmployeeNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSearchEmployeeName)
                    .addComponent(jTextFieldSearchEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSearchOR))
                .addGap(38, 38, 38)
                .addComponent(jButtonSearchSubmit)
                .addGap(38, 38, 38)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(223, Short.MAX_VALUE))
        );

        jTabbedPaneMain.addTab("Search", jPanelSearch);

        jPanelView.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Employee Number", "First Name", "Last Name", "Location", "Net Income"
            }
        ));
        jScrollPaneViewAllEmployees.setViewportView(jTable1);

        jLabel12.setText("Use tiles to display employee information if <br/>capable of doing so with code to repeat the tiles");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 24)); // NOI18N
        jLabel1.setText("View All");

        javax.swing.GroupLayout jPanelViewLayout = new javax.swing.GroupLayout(jPanelView);
        jPanelView.setLayout(jPanelViewLayout);
        jPanelViewLayout.setHorizontalGroup(
            jPanelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelViewLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPaneViewAllEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelViewLayout.setVerticalGroup(
            jPanelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelViewLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelViewLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPaneViewAllEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(161, Short.MAX_VALUE))
        );

        jTabbedPaneMain.addTab("View All", jPanelView);

        jMenuBarMenu.setBackground(new java.awt.Color(100, 100, 100));
        jMenuBarMenu.setBorder(null);

        jMenuFile.setText("File");
        jMenuFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFileActionPerformed(evt);
            }
        });

        jMenuItemFileNew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemFileNew.setText("New");
        jMenuFile.add(jMenuItemFileNew);

        jMenuItemFileOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemFileOpen.setText("Open");
        jMenuItemFileOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFileOpenActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemFileOpen);

        jMenuItemFileSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemFileSave.setText("Save");
        jMenuFile.add(jMenuItemFileSave);

        jMenuItemFileSaveAs.setText("Save As");
        jMenuFile.add(jMenuItemFileSaveAs);

        jMenuItem1.setText("Exit");
        jMenuFile.add(jMenuItem1);

        jMenuBarMenu.add(jMenuFile);

        jMenuWindow.setText("Window");

        jMenuItemWindowPreferences.setText("Preferences");
        jMenuWindow.add(jMenuItemWindowPreferences);

        jMenuBarMenu.add(jMenuWindow);

        jMenuHelp.setText("Help");

        jMenuItemHelpCheckForUpdates.setText("Check for Updates");
        jMenuItemHelpCheckForUpdates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHelpCheckForUpdatesActionPerformed(evt);
            }
        });
        jMenuHelp.add(jMenuItemHelpCheckForUpdates);

        jMenuItemHelpAbout.setText("About");
        jMenuHelp.add(jMenuItemHelpAbout);

        jMenuItemHelpTutorial.setText("Tutorial");
        jMenuHelp.add(jMenuItemHelpTutorial);

        jMenuItemHelpDocumentation.setText("Documentation");
        jMenuHelp.add(jMenuItemHelpDocumentation);

        jMenuBarMenu.add(jMenuHelp);

        setJMenuBar(jMenuBarMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneMain, javax.swing.GroupLayout.PREFERRED_SIZE, 777, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPaneMain)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuFileActionPerformed

    private void jMenuItemFileOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFileOpenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemFileOpenActionPerformed

    private void jMenuItemHelpCheckForUpdatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHelpCheckForUpdatesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemHelpCheckForUpdatesActionPerformed

    private void jButtonSearchSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchSubmitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSearchSubmitActionPerformed

    private void jRadioButtonAddSexMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAddSexMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonAddSexMActionPerformed

    private void jButtonHomeExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonHomeExitActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jRadioButtonAddPartTimeEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAddPartTimeEmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonAddPartTimeEmployeeActionPerformed

    private void jRadioButtonAddFullTimeEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAddFullTimeEmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonAddFullTimeEmployeeActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonAddSubmit;
    private javax.swing.JButton jButtonHomeExit;
    private javax.swing.JButton jButtonSearchSubmit;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelAddDeductRate;
    private javax.swing.JLabel jLabelAddEmployeeNumber;
    private javax.swing.JLabel jLabelAddFirstName;
    private javax.swing.JLabel jLabelAddFullTimeEmployeeYearlySalary;
    private javax.swing.JLabel jLabelAddHeading;
    private javax.swing.JLabel jLabelAddLastName;
    private javax.swing.JLabel jLabelAddLocation;
    private javax.swing.JLabel jLabelAddPartTimeEmployeeHourlyWage;
    private javax.swing.JLabel jLabelAddPartTimeEmployeeHoursPerWeek;
    private javax.swing.JLabel jLabelAddPartTimeEmployeeWeeksPerYear;
    private javax.swing.JLabel jLabelAddSex;
    private javax.swing.JLabel jLabelHomeCurrentCEO;
    private javax.swing.JLabel jLabelHomeEmployeeCount;
    private javax.swing.JLabel jLabelHomeHeading;
    private javax.swing.JLabel jLabelHomePayrollTotal;
    private javax.swing.JLabel jLabelHomeWorkforceHours;
    private javax.swing.JLabel jLabelSearchEmployeeName;
    private javax.swing.JLabel jLabelSearchEmployeeNumber;
    private javax.swing.JLabel jLabelSearchHeading;
    private javax.swing.JLabel jLabelSearchOR;
    private javax.swing.JMenuBar jMenuBarMenu;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemFileNew;
    private javax.swing.JMenuItem jMenuItemFileOpen;
    private javax.swing.JMenuItem jMenuItemFileSave;
    private javax.swing.JMenuItem jMenuItemFileSaveAs;
    private javax.swing.JMenuItem jMenuItemHelpAbout;
    private javax.swing.JMenuItem jMenuItemHelpCheckForUpdates;
    private javax.swing.JMenuItem jMenuItemHelpDocumentation;
    private javax.swing.JMenuItem jMenuItemHelpTutorial;
    private javax.swing.JMenuItem jMenuItemWindowPreferences;
    private javax.swing.JMenu jMenuWindow;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelAdd;
    private javax.swing.JPanel jPanelHome;
    private javax.swing.JPanel jPanelSearch;
    private javax.swing.JPanel jPanelView;
    private javax.swing.JRadioButton jRadioButtonAddFullTimeEmployee;
    private javax.swing.JRadioButton jRadioButtonAddPartTimeEmployee;
    private javax.swing.JRadioButton jRadioButtonAddSexF;
    private javax.swing.JRadioButton jRadioButtonAddSexM;
    private javax.swing.JRadioButton jRadioButtonAddSexOther;
    private javax.swing.JRadioButton jRadioButtonAddSexPreferNot;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPaneViewAllEmployees;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPaneMain;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextFieldAddDeductRate;
    private javax.swing.JTextField jTextFieldAddEmployeeNumber;
    private javax.swing.JTextField jTextFieldAddFirstName;
    private javax.swing.JTextField jTextFieldAddFullTimeEmployeeYearlySalary;
    private javax.swing.JTextField jTextFieldAddLastName;
    private javax.swing.JTextField jTextFieldAddPartTimeEmployeeHourlyWage;
    private javax.swing.JTextField jTextFieldAddPartTimeEmployeeHoursPerWeek;
    private javax.swing.JTextField jTextFieldAddPartTimeEmployeeWeeksPerYear;
    private javax.swing.JTextField jTextFieldSearchEmployeeName;
    private javax.swing.JTextField jTextFieldSearchEmployeeNumber;
    // End of variables declaration//GEN-END:variables
}
